language: go
go:
- '1.10'
services:
- docker
script:
- make docker
before_deploy:
- sudo apt-get -y install python-requests
- echo "Now cleaning up unused draft releases from repo $GITHUB_REPO"
- python tools/github_purge_draft_releases.py $GITHUB_REPO $GITHUB_TOKEN
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file:
  - naksu_windows_amd64.zip
  - naksu_linux_amd64.zip
  draft: true
  skip_cleanup: true
  on:
    repo: $GITHUB_REPO
